### ISSUE TITLE
import pyczmq

### ISSUE THREAD

**Issue by erhuabushuo** [zeromq/pyczmq#26]
from _cffi import C, ffi
ImportError: No module named '_cffi'

**Comment by claws** [comment]
This issue has almost no information to help us help you. Perhaps you could provide information such as the O/S, Python version, etc. Did you follow the instructions in the readme? 

I just cloned the repo and ran the unit tests which all passed. Seems to be working just fine for me on Ubunutu14:04, python2.7 with the libffi-dev, czmq, etc dependencies installed.

**Comment by myd7349** [comment]
I am using Python 3.x, so:
```python
from . _cffi import C, ffi
```
works.
